### ISSUE TITLE
Contract code deep linking

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-frontend#10]
Enable deep linking on contract code page.
E.g.: `/contract/eos/crypto/binance/ETH%2FBTC?updatefreq=10&lifetime=11`
Deep linking should mirror REST API URIs.

**Comment by alerdenisov** [comment]
What is deep linking? Should we parse url params to generator configuration?

**Comment by MaxSvargal** [comment]
https://github.com/DucaturFw/ducor-frontend/commit/a368372c29b5b15d8ea4604b3ed60430b00439de
