### ISSUE TITLE
Router not working on new page load

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-frontend#2]
1. Open `/`
`/` works
2. Click on any button to go to `/construct`
`/construct` works
3. Open `/construct` in a new browser window
`/construct` returns HTTP 404

![image](https://user-images.githubusercontent.com/1829671/43089505-76ed9580-8ead-11e8-9060-a5c4a1ec5f57.png)

**Comment by MaxSvargal** [comment]
It lad down this will fix on nginx side with simple config like
`location / {
    try_files /index.html;
}`

**Comment by MaxSvargal** [comment]
Fixed for dev server
