### ISSUE TITLE
Footer is not fixed-height

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-frontend#3]
Footer is not glued to the bottom of the screen, moves too high on pages with short content

![image](https://user-images.githubusercontent.com/1829671/43089811-4ee67736-8eae-11e8-82be-f21c1b7f2335.png)
![image](https://user-images.githubusercontent.com/1829671/43089831-5e186d4a-8eae-11e8-9814-025e16938063.png)

**Comment by zlumer** [comment]
[1h]

**Comment by MaxSvargal** [comment]
https://github.com/DucaturFw/ducor-frontend/commit/b01f6691e8fb5aad13fce2fab6f8f24c68a007e8
