### ISSUE TITLE
Extra columns should only appear after completing prevous step

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-frontend#4]
E.g.: `Data provider` should only appear after user selected `Currency pair`.
Contract settings should only appear after user selected `Data provider`.
`Generate` button should stay disabled until the last step (becomes enabled when contract settings appear).

![image](https://user-images.githubusercontent.com/1829671/43089981-cdafcda6-8eae-11e8-8475-ec059ffdbc29.png)

**Comment by MaxSvargal** [comment]
This states don't isset on prototypes.
No state for main button.
No state for column then they disabled.

**Comment by zlumer** [comment]
Mostly done in #18, now we only need to disable the `Generate` button.

**Comment by MaxSvargal** [comment]
https://github.com/DucaturFw/ducor-frontend/issues/20
